### PR TITLE
Proper children reconcile for nested tags

### LINKED ISSUE #869: Uncaught Error: removeComponentAsRefFrom(...)
4.0.0-rc.0
React 15.6.2

Multiple `React-hot-loader: unable to merge` top-level components, followed by 
> Uncaught Error: removeComponentAsRefFrom(...): Only a ReactOwner can have refs. You might be removing a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

In the same time - it is working as expected, doing it's work.

4.0.0-beta.20 - the same
4.0.0-beta.19 - the same
4.0.0-beta.15-19 - nothing works, everything got unmounted.

4.0.0-beta.13-14 - less of `unable to merge`, all about low-level components. Working.

React 16.2.0 - the same `unable to merge`, but **no errors**.

Code to reproduce: not extracted yet. Just filling the issue.

In all the cases `unable to merge` solved by sub-renders. This is just a parasite error message for React 15. Will try to solve the merge problem, as long it is a single pattern - I was just happy to have in my personal project.

### PR DESCRIPTION
**Pull request by theKashey**
Proper children reconcile for nested tags, fixes #869

The way a change the tests indicates that problem was fixed.

### CODE REVIEW

File: src/reconciler/hotReplacementRender.js [hunk 1]
```diff
@@ -129,17 +129,19 @@ const mapChildren = (children, instances) => ({
       }
     }
 
-    const newChildren = asArray((child.props && child.props.children) || [])
+    const newChildren = asArray(
+      (child.props && child.props.children) || child.children || [],
```
Comment (theKashey) [inline src/reconciler/hotReplacementRender.js]: When result of this function on next render iteration got in here again - it will be just ignored.
That was the first problem.

File: src/reconciler/hotReplacementRender.js [hunk 2]
```diff
@@ -129,17 +129,19 @@ const mapChildren = (children, instances) => ({
...
 
     return {
       ...instanceLine,
-      // actually child merge is needed only for TAGs, and usually don't work for Components.
+      // actually child merge is needed only for "HTML TAG"s, and usually don't work for Components.
       // the children from an instance or rendered children
       // while children from a props is just a props.
       // they could not exists. they could differ.
-      ...(nextChildren ? { children: nextChildren } : {}),
+      ...(nextChildren || {}),
```
Comment (theKashey) [inline src/reconciler/hotReplacementRender.js]: This was a second. A little "gap" in the tree

File: test/reconciler.test.js [hunk 3]
```diff
@@ -213,12 +213,50 @@ describe('reconciler', () => {
 
       incrementGeneration()
       wrapper.setProps({ update: 'now' })
-      expect(First.rendered).toHaveBeenCalledTimes(4)
+      expect(First.rendered).toHaveBeenCalledTimes(3)
```
Comment (theKashey) [inline test/reconciler.test.js]: This means - fixed!
